language: python

python:
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - pip install coveralls --use-mirrors

script:
  - coverage run --source=hachi setup.py test

after_success:
  - coveralls

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#hachi"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
